server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/app
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

keycloak:
  base-url: ${KEYCLOAK_BASE_URL}
  token-endpoint: /realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
  user-endpoint: /admin/realms/${KEYCLOAK_REALM}/users
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}